name: ccs

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./dataframes:/dataframes
      - ./logs:/logs
      - ./metrics:/metrics
      - ./models:/models
      - ./notebooks:/notebooks
      - ./cache:/cache

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./logs:/var/log/nginx/
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
